### ISSUE TITLE
Incorrect link to the battle voices in the readme

### ISSUE THREAD

**Issue by mijkami** [leycec/kiseki-linux#2]
This is a minor problem but it could be puzzling to some users.

The current link goes to the [MEGA-hosted filelocker folder](https://mega.nz/folder/QkFDgLBC#UiLo3rUekisptpzONidpmw/folder/U1933IaT) used for the **Japanese dialogue voices** linked just before, instead of this link to the [actual folder of the **Japanese battle voices**](https://mega.nz/folder/QkFDgLBC#UiLo3rUekisptpzONidpmw/folder/40FgxYaA).

**Comment by leycec** [comment]
**Yikes!** Thanks for that last-minute catch. I'll get this squared away right away.

Let me know if there's anything else we can do for you, @mijkami. I'd especially love to know whether gamepad support behaves as expected. I keep meaning to test this myself with a good ol' DualShock 4 (DS4), but one pull request leads to another and... *here we still are.* `</sigh>`

**Comment by leycec** [comment]
By your command, **it is done.** :fist_raised: 

The [*Browse to this MEGA-hosted filelocker folder*](https://mega.nz/folder/QkFDgLBC#UiLo3rUekisptpzONidpmw/folder/40FgxYaA) link now references the expected folder, thanks entirely to your valiant efforts. You are the ultimate Bracer.
