### ISSUE TITLE
Update SoraVoice Lite to the latest version

### ISSUE THREAD

**Issue by themaster567** [leycec/kiseki-linux#6]
Hey there, me again! I finally had time to actually sit down and play, when I discovered to my abject **_horror_** that there wasn't any voice acting! Shocked, petrified, unable to move, I stared blankly down at my Steam Deck, then everything went black. The trauma was too much to bear.

At least seven hours later, I regained consciousness and picked myself up off the floor. After having a nutritious glass of several thousand spiders, I decided to try and investigate what could be causing this problem. 

**It turns out that there was an update to the game in January of 2022 that was incompatible with SoraVoice Lite. If you download the latest update for SoraVoice and overwrite everything, the voices work as they should.**

Problem solved!

**Comment by leycec** [comment]
>  I finally had time to actually sit down and play...

![dat smile tho](https://pbs.twimg.com/media/ET0nHL9X0AI_3nr?format=jpg&name=small)

> ...when I discovered to my abject **_horror_** that there wasn't any voice acting!

![broken soul moment](https://static1.cbrimages.com/wordpress/wp-content/uploads/2019/12/Gintama-Meme-Feature.jpg?q=50&fit=contain&w=943&h=&dpr=1.5)

> At least seven hours later, I regained consciousness and picked myself up off the floor.

![that next-day feeling](https://c.tenor.com/v-NmWiYZz-QAAAAC/gintama-anime.gif)

> **It turns out that there was an update to the game in January of 2022 that was incompatible with SoraVoice Lite. If you download the latest update for SoraVoice and overwrite everything, the voices work as they should.**

![rejoice everyone](https://static.wikia.nocookie.net/gintama/images/1/13/Hasegawa_and_gin.png/revision/latest/scale-to-width-down/1281?cb=20160606031616)

Thanks *so* much for your dizzying descent into the annals of madness, @themaster567. Clearly, you are a rising star of many talents. I really appreciate the precious weekend moments you invested into this. Praise be to the Bright Family that your solution trivially reduces to a dependency bump. Dodged an Aural Blast S-craft on that one, folks!

I've summarily resolved this for everyone in 58dd4ba. May your every combat be swift and the monsters fall like chaff before your absurdly overpowered Twin Plovers. :crossed_swords:
